@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package architectspalette.content.blocks.flint;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;