@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package architectspalette.content.blocks.entrails;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;