@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package architectspalette.content.blocks.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;