@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package architectspalette.compat;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;