@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package architectspalette.content.blocks.abyssaline;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;