@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package architectspalette.content.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;